apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flogowebui
spec:
  replicas: 2
  selector: 
    matchLabels:
	  app: flogowebui
  template:
    metadata:
	  labels:
	    app: flogowebui
	spec:
	  containers:
	  - name: flogowebui
	    image: flogo/flogo-docker
		ports:
		- containerPort: 3303
---
apiVersion: v1
kind: Service
metadata:
  name: flogowebui-svc
spec:
  ports:
  - port: 3303
    targetPort: 3303
    protocol: TCP
	name: http
  selector:
    app: flogowebui
